# **A. Numpy Practice (75 points)**

In [1]:
import numpy as np
from typing import List, Dict, Tuple, Optional

### **Q1: Vector Initialization**

Initialize a vector consisting entirely of `N` zero elements.

Example:

Input: 
```
N = 5
```

Output:
```
array([0., 0., 0., 0., 0.])
```

In [2]:
def init_zeros(n: int) -> np.ndarray:
    ### BEGIN SOLUTION
    return np.zeros(n)
    ### END SOLUTION

In [6]:
# Sample Input & Output
init_zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
# Public Test
assert init_zeros(5).shape == (5, )
assert np.sum(abs(init_zeros(5) - np.array([0, 0, 0, 0, 0]))) == 0

### **Q2: Vector Initialization**

Initilize a vector consisting entirely of `N` one elements.

Example:

Input:
```
N = 5
```

Output:
```
array([1., 1., 1., 1., 1.])
```

In [7]:
def init_ones(n: int) -> np.ndarray:
    ### BEGIN SOLUTION
    return np.ones(n)
    ### END SOLUTION

In [8]:
# Sample Input & Output
init_ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
# Public Test
assert init_ones(5).shape == (5, )
assert np.sum(abs(init_ones(5) - np.array([1, 1, 1, 1, 1]))) == 0

### **Q3: Vector Initialization**

Initialize a vector of `N` elements consisting entirely of numbers `x`.

Example:

Input:

```N = 5 ```

```x = 3.5 ```

Output:
```
array([3.5, 3.5, 3.5, 3.5, 3.5])
```

In [12]:
def init_all_x(n: int, x: float) -> np.ndarray:
    ### BEGIN SOLUTION
    return np.full(n,x)
    ### END SOLUTION

In [13]:
# Sample Input & Output
init_all_x(5, 3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5])

In [14]:
# Public Test
assert init_all_x(5, 3.5).shape == (5, )
assert np.sum(abs(init_all_x(5, 3.5) - np.array([3.5, 3.5, 3.5, 3.5, 3.5]))) == 0

### **Q4: Vector Initialization**

Initialize a vector of `N` elements consisting of integers in increasing order from `0..n-1`.

Example:

Input:

```N = 5 ```

Output:
```
array([0, 1, 2, 3, 4])
```

In [15]:
def init_range(n: int) -> np.ndarray:
    ### BEGIN SOLUTION
    return np.arange(n)
    ### END SOLUTION

In [16]:
# Sample Input & Output
init_range(5)

array([0, 1, 2, 3, 4])

In [17]:
# Public Test
assert init_range(5).shape == (5, )
assert np.sum(abs(init_range(5) - np.array([0,1,2,3,4]))) == 0

### **Q5: Vector Initialization**

Initialize a vector of `N` elements consisting of integers in increasing order from `x, x+1,..., x+n-1`.

Example:

Input:

```N = 5 ```

```x = 3.5 ```

Output:
```
array([3.5, 4.5, 5.5, 6.5, 7.5])
```

In [18]:
def init_range(n: int, x: int) -> np.ndarray:
    ### BEGIN SOLUTION
    return np.arange(x,x+n)
    ### END SOLUTION

In [19]:
# Sample Input & Output
init_range(5, 3.5)

array([3.5, 4.5, 5.5, 6.5, 7.5])

In [20]:
# Public Test
assert init_range(5, 3).shape == (5, )
assert np.sum(abs(init_range(5, 3) - np.array([3, 4, 5, 6, 7]))) == 0

### **Q6: Matrix Initialization**

Initialize an m x n matrix consisting entirely of `K` numbers.

Example:

Input:

```
m = 3
n = 4
K = 5
```

Output:
```
array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])
```

In [26]:
def init_mat_K(m: int, n: int, K: float) -> np.ndarray:
    ### BEGIN SOLUTION
    return  np.full((m, n), K, dtype=float)
    ### END SOLUTION

In [27]:
# Sample Input & Output
init_mat_K(3, 4, 5)

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [28]:
# Public Test
assert init_mat_K(2,3,4).shape == (2, 3)
assert np.sum(abs(init_mat_K(2,3,4) - np.array([[4, 4, 4], [4, 4, 4]]))) == 0

### **Q7: Matrix Initialization**

Initialize an m x n matrix by incrementing from left to right and from top to bottom. The smallest element starts at 1.

Example:

Input:
```
m = 2
n = 4
```

Output:
```
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
```

In [29]:
def init_mat_increase(m: int, n: int) -> np.ndarray:
    ### BEGIN SOLUTION
    return np.arange(1, m * n + 1).reshape(m, n)    
    ### END SOLUTION

In [30]:
# Sample Input & Output
init_mat_increase(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
# Public Test
assert init_mat_increase(2,3).shape == (2, 3)
assert np.sum(abs(init_mat_increase(2,3) - np.array([[1, 2, 3], [4, 5, 6]]))) == 0

### **Q8: Dot Product of Two Vectors**

Write a function that takes two lists `a` and `b` of data type `float` as input, and calculates the dot product between the two vectors `a` and `b`.

Example:

Input:
```
a = [1, 2]
b = [3, 4]
```

Output:
```
11
```

In [35]:
def product_on_list(a: List[int], b: List[int]) -> np.ndarray:
    # Step 1: Convert a and b to numpy arrays
    ### BEGIN SOLUTION
    a = np.array(a)
    b = np.array(b)
    ### END SOLUTION

    # Step 2: Calculate dot product using the dot function
    ### BEGIN SOLUTION
    return np.dot(a, b)
    ### END SOLUTION

In [33]:
# Sample Input & Output
product_on_list([1, 2], [2, 3])

np.int64(8)

In [34]:
# Public Test
assert product_on_list([1, 2], [2, 3]) == 8
assert product_on_list([1, 2], [0, 0]) == 0

### **Q9: Dot Product of Two Matrices**

Write a function that takes two matrices `X` and `W` as input and returns the dot product `M` using the following formula:

```
M = (x^T)W
```
Where `x^T` is the transpose of `x`. The dimension needs to be checked to ensure the calculation is always possible before performing the calculation, returning `None` if the dimension is incompatible.

Example:

Ví dụ:


Input:
```
X = np.array([
    [1, 1, 1],
    [0, 0, 0]]
)

W = np.array([
    [1, 1, 1],
    [0, 0, 0]]
)
```

Output:
```
[[1, 1, 1],
 [1, 1, 1],
 [1, 1, 1]]
```

In [36]:
def product_vec_mat(X: np.ndarray, W: np.ndarray) -> Optional[np.ndarray]:
    ### BEGIN SOLUTION
    XT = X.T
    if XT.shape[1] != W.shape[0]:
        return None
    return np.dot(XT, W)
    ### END SOLUTION

In [37]:
# Sample Input & Output
X = np.array([
  [1, 1, 1],
  [0, 0, 0]
])
W = np.array([
  [1, 1, 1],
  [0, 0, 0]
])
product_vec_mat(X, W)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [38]:
# Public Test
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
W = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

assert np.sum(abs(product_vec_mat(X, W)-np.array([
    [47, 52, 57],
    [64, 71, 78],
    [81, 90, 99]
]))) < 0.0001

### **Q10: Sum of Matrices and Vectors**

Write a function that takes two matrices `X` and `W` as input and returns the value `M` according to the following formula:
```
M = 2 (X^T + W).X
```
Where `X^T` is the transpose of `X`. The dimension needs to be checked to ensure the calculation is always possible before performing the calculation, returning `None` if the dimension is incompatible.

Example:

Input:
```
X = np.array([
    [1, 1],
    [0, 0]
])

W = np.array([
    [1, 1],
    [0, 0]
])
```

Output:
```
array([[4, 4],
       [2, 2]])
```

In [39]:
def prod_sum_mat(x: np.ndarray, w: np.ndarray) -> Optional[np.ndarray]:
    ### BEGIN SOLUTION
    XT = X.T

    if XT.shape != W.shape:
        return None

    temp = XT + W

    if temp.shape[1] != X.shape[0]:
        return None

    return 2 * np.dot(temp, X)
    ### END SOLUTION

In [40]:
# Public Test
X = np.array([
  [1, 1],
  [2, 3],
  [5, 4]
])

W = np.array([
  [1, 2, 3],
  [4, 5, 6]
])

assert np.sum(abs(prod_sum_mat(X, W)-np.array([
    [100, 92],
    [142, 138]
]))) < 0.0001

### **Q11: Savings Deposit**

Calculate the remaining balance in a bank account with the input being a list of transaction amounts, corresponding to a list of deposit transaction types (debit, denoted by the string 'D'), withdrawal transaction types (debit, denoted by the string 'W')

**Input:**
- moneys: a numpy array containing a list of transaction amounts (deposits and withdrawals from the account)

- types: a numpy array containing a list of transaction types (deposits denoted by 'D', withdrawals denoted by 'W')

**Output:**
- A real number, the remaining balance in the account

Example:

Input:
```
moneys = [400.0, 100.0, 200.0]
types = ['D', 'W', 'D']
```

Output:
```
500.0
```

In [41]:
def balance(moneys: np.ndarray, types: np.ndarray) -> float:
    ### BEGIN SOLUTION
    moneys = np.array(moneys, dtype=float)
    types = np.array(types)

    deposits = np.sum(moneys[types == 'D'])
    withdrawals = np.sum(moneys[types == 'W'])

    return deposits - withdrawals
    ### END SOLUTION

In [42]:
# Sample Input & Output
balance(np.array([400.0, 100.0, 200.0]), np.array(['D', 'W', 'D']))

np.float64(500.0)

In [43]:
# Public Test
assert balance(np.array([400.0, 100.0, 200.0]), np.array(['D', 'W', 'D'])) == 500

### **Q12: Average Grade**

Calculate the average grade of a student given a list of grades and credits for each course.

**Input:**
- marks: List type, containing *n* elements. This is the grade for each course.
- credits: List type, containing *n* elements. This is the number of credits for each course.

**Output:**
- Real number type, the average grade for each course.

Example:

Input:
```
marks = [8.0, 9.0, 10.0]
credits = [2, 2, 1]
```

Output:
```
8.8
```

In [44]:
def gpa_one_student(marks: List[float], credits: List[int]) -> float:
    result = 0
    ### BEGIN SOLUTION
    marks = np.array(marks, dtype=float)
    credits = np.array(credits)

    # Calculate weighted average
    result = np.dot(marks, credits) / np.sum(credits)
    ### END SOLUTION
    return result

In [45]:
# Sample Input & Output
marks = [8.0, 9.0, 10.0]
credits = [2, 2, 1]
gpa_one_student(marks, credits)

np.float64(8.8)

In [46]:
# Public Test
assert abs(gpa_one_student([10, 9, 8], [4, 3, 2])-9.222222222222221) < 0.000001

### **Q13**

Count the number of students in a class whose score is at least K points.

**Input:**
- marks: a numpy array, size 1 x n. This is the math score of all n students in the class.
- K: a real number, the benchmark score.

**Output:**
- Number of students (integer) in the class who scored K points or higher.

In [48]:
def pass_exam(marks: np.array, K: float) -> int:
    ### BEGIN SOLUTION
    marks = np.array(marks)

    return np.sum(marks >= K)
    ### END SOLUTION

In [49]:
# Sample Input & Output
marks = np.array([4.0, 9.0, 5.0])
K = 5
pass_exam(marks, K)

np.int64(2)

In [50]:
# Public Test
assert pass_exam(np.array([3.0, 9.5, 4.5]), 5.0) == 1

### **Q14**

Calculate the highest average score of a class given a list of scores and credits for each subject in the class.

**Input:**
- marks: numpy array, size m x n. This is the score for each subject in the class. 
    - m is the number of students
    - n is the number of subjects.
- credits: numpy array, size 1 x n. This is the number of credits for each subject.

**Output:**
- Real number, the average score of the highest-scoring student.

Example:

Input:
```
marks = np.array(
   [[8.0, 9.0, 10.0],
   [7.0, 9.0, 8.0],
   [8.0, 8.0, 8.0],
   [10.0, 9.0, 7.0],
   [9.0, 9.0, 10.0]
])

credits = np.array([2,2,1])
```

Output:
```
9.2
```

In [51]:
def max_gpa(marks: np.array, credits: np.array) -> float:
    ### BEGIN SOLUTION
    averages = np.dot(marks, credits) / np.sum(credits)

    return np.max(averages)
    ### END SOLUTION

In [52]:
# Sample Input & Output
marks = np.array(
   [[8.0, 9.0, 10.0],
   [7.0, 9.0, 8.0],
   [8.0, 8.0, 8.0],
   [10.0, 9.0, 7.0],
   [9.0, 9.0, 10.0]
])
credits = np.array([2,2,1])
max_gpa(marks, credits)

np.float64(9.2)

In [53]:
# Public Test
marks = np.array(
   [[4.0, 9.0, 4.5],
   [5.0, 8.0, 4.5],
   [6.0, 7.0, 7.5],
   [7.0, 6.0, 7.5],
   [8.0, 5.0, 4.5]
])
credits = np.array([2,1,2])
assert abs(max_gpa(marks, credits)-7.0) < 0.000001

### **Q15**

Calculate the cumulative GPA of each student in a class given a list of scores and credits for each subject in the class.

Note: When calculating the GPA, we will exclude scores and credits for subjects below 5 points (failed).

**Formula for calculating the cumulative GPA:**
- GPA = (score for subject 1 * number of credits for subject 1 + ... + score for subject n * number of credits for subject n) / total number of credits

**Input:**
- marks: numpy array, size m x n. This is the score for each subject in the class.
    - m is the number of students
    - n is the number of subjects.
- credits: numpy array, size 1 x n. This is the number of credits for each subject.

**Output:**
- numpy array, size 1 x m, containing the average scores of the students in the class.

Example:

Input:
```
marks = np.array([
    [8.0, 9.0, 10.0],
    [4.0, 9.0, 8.0],
    [8.0, 3.0, 8.0],
    [10.0, 9.0, 5.0],
    [9.0, 9.0, 4.0]
])

credits = np.array([2, 2, 1])
```

Output:
```
array([8.8, 8.66666667, 8., 8.6, 9.])
```

In [54]:
def gpa_of_pass(marks: np.ndarray, credits: np.array) -> np.ndarray:
    ### BEGIN SOLUTION
    passed = marks >= 5

    weighted_scores = np.sum(marks * credits * passed, axis=1)

    total_credits = np.sum(credits * passed, axis=1)

    return weighted_scores / total_credits
    ### END SOLUTION

In [55]:
# Sample Input & Output
marks = np.array(
    [[8.0, 9.0, 10.0],
    [4.0, 9.0, 8.0],
    [8.0, 3.0, 8.0],
    [10.0, 9.0, 5.0],
    [9.0, 9.0, 4.0]])
credits = np.array([2,2,1])
gpa_of_pass(marks, credits)

array([8.8       , 8.66666667, 8.        , 8.6       , 9.        ])

In [56]:
# Public Test
marks = np.array(
   [[4.0, 9.0, 4.5],
   [5.0, 8.0, 4.5],
   [6.0, 7.0, 7.5],
   [7.0, 6.0, 7.5],
   [8.0, 5.0, 4.5]])
credits = np.array([2,1,2])
assert np.sum(abs(gpa_of_pass(marks, credits)-np.array([9., 6., 6.8, 7.0, 7.0]))) < 0.000001

# **B. OOP Practice (25 points)**

### **Q1 (15 points)**

Write a program to implement the following three classes: `Geometry`, `Square`, and `Round`. Indicate that the `Square` and `Round` classes inherit from the `Geometry` class.

All three classes have the following properties and methods:
- Properties:
    - `property` (`float`): can be considered the side length (for a square) or radius (for a circle).
- Methods:
    - Constructor `__init__`.
    - Area calculation function `calculate_area`.

-----

Example of the `calculate_area` function of the `Square` class:
- Object properties:
```
property = 2
```
- Input:
```
# no input
```
- Output:
```
4
```
-----

Example of the `calculate_area` function of the `Round` class:
- Object properties:
```
property = 2
```
- Input:
```
# no input
```
- Output:
```
12.56637
```

Note: Use `math.pi` to calculate the area; the result is rounded to 5 decimal places.

##### **Requirement 1:** 

Implement the `Geometry` class. Set the `calculate_area` method to an `abstract method`.

In [57]:
from abc import abstractmethod
from typing import List, Dict, Tuple, Optional

### BEGIN SOLUTION
class Geometry:
    def __init__(self, property: float):
        self.property = property

    @abstractmethod
    def calculate_area(self):
        pass


class Square(Geometry):
    def __init__(self, property: float):
        super().__init__(property)

    def calculate_area(self):
        return self.property ** 2


class Round(Geometry):
    def __init__(self, property: float):
        super().__init__(property)

    def calculate_area(self):
        return round(math.pi * (self.property ** 2), 5)
### END SOLUTION

In [58]:
# Public Test
geometry_obj = Geometry(2)
assert geometry_obj.property == 2

##### **Requirement 2:** 

Implement the `Square` class that inherits from the `Geometry` class.

In [59]:
class Square(Geometry):
    def __init__(self, property: float) -> None:
        # Call the __init__ method of the parent class using `super()`
        ### BEGIN SOLUTION
        super().__init__(property)
        ### END SOLUTION

    # Implement the `calculate_area` method
    ### BEGIN SOLUTION
    def calculate_area(self):
        return self.property ** 2
    ### END SOLUTION

In [60]:
# Public Test
square_obj = Square(2)
assert square_obj.calculate_area() == 4

##### **Requirement 3:** 

Implement a class `Round` that inherits from the `Geometry` class. Note that you should use `math.pi` and round the results to 5 decimal places.

In [61]:
import math

class Round(Geometry):
    def __init__(self, property: float) -> None:
        # Call the __init__ method of the parent class using `super()`
        ### BEGIN SOLUTION
        super().__init__(property)
        ### END SOLUTION

    # Implement the `calculate_area` method
    ### BEGIN SOLUTION
    def calculate_area(self):
        return round(math.pi * (self.property ** 2), 5)
    ### END SOLUTION

In [62]:
# Public Test
square_obj = Round(2)
assert square_obj.calculate_area() == 12.56637

### **Q2 (10 points)**

Write a program to implement the class `Fraction`.

The class has the following attributes and methods:

- Attributes:
    - `numerator` (int).
    - `denominator` (int) (conditional, not 0; use the `assert` statement to check during declaration).
- Methods:
    - Constructor `__init__`: Note that it returns an error if the denominator is declared as 0. Note that fractions are simplified.
    - Calculation functions: `add`, `subtract`:
    - Updates `numerator` and `denominator` of the object; note that fractions are simplified.

- Fraction reduction function: `reduction`.

**Convention:** If the numerator is 0, assign the denominator to 1.

----

Example 1 of the `__init__` function:
- Input:
```
numerator = 2
denominator = 4
```
- Output:
```
# no output
```
- Properties of the object after execution:
```
numerator = 1
denominator = 2
```

----

Example 2 of the `__init__` function:
- Input:
```
numerator = 2
denominator = 0
```
- Output:
```
# error
```
- Properties of the object after execution:
```
# error
```

----

Example of the `add` function (add fractions):
- Object properties:
```
numerator = 1
denominator = 3
```
- Input:
```
other = Fraction(1, 3)
```
- Output:
```
# no output
```
- Object properties after execution:
```
numerator = 2
denominator = 3
```

----

Example of the `subtract` function (subtracting fractions):
- Object properties:
```
numerator = 2
denominator = 3
```
- Input:
```
other = Fraction(1, 3)
```
- Output:
```
# no output
```
- Object properties after execution:
```
numerator = 1
denominator = 3
```

##### **Requirement**: Implement `Fraction` class.

In [75]:
import math


class Fraction:
    def __init__(self, numerator: int, denominator: int) -> None:
        # Check denominator
        assert denominator != 0, "Denominator cannot be 0"

        # English attributes
        self.numerator = numerator
        self.denominator = denominator

        # Vietnamese aliases
        self.tu_so = self.numerator
        self.mau_so = self.denominator

        self.reduction()

    def reduction(self) -> None:
        if self.numerator == 0:
            self.denominator = 1
        else:
            gcd = math.gcd(self.numerator, self.denominator)

            self.numerator //= gcd
            self.denominator //= gcd

            # Make denominator positive
            if self.denominator < 0:
                self.numerator *= -1
                self.denominator *= -1

        # Update aliases
        self.tu_so = self.numerator
        self.mau_so = self.denominator

    def add(self, other: 'Fraction') -> None:
        self.numerator = (
            self.numerator * other.denominator
            + other.numerator * self.denominator
        )

        self.denominator *= other.denominator
        self.reduction()

    def subtract(self, other: 'Fraction') -> None:
        self.numerator = (
            self.numerator * other.denominator
            - other.numerator * self.denominator
        )

        self.denominator *= other.denominator
        self.reduction()

    # Vietnamese alias
    def tru(self, other: 'Fraction') -> None:
        self.subtract(other)

In [76]:
# Public Test
fraction_obj = Fraction(2, 4)
assert fraction_obj.numerator == 1
assert fraction_obj.denominator == 2

In [77]:
# Public Test
try:
    has_error = False
    Fraction(1, 0)
except:
    has_error = True

assert has_error

In [78]:
# Public Test
fraction_obj = Fraction(2, 3)
fraction_obj.tru(Fraction(1, 3))
assert fraction_obj.tu_so == 1
assert fraction_obj.mau_so == 3